# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TumConf.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TUMCONF(object):
    def setupUi(self, TUMCONF):
        TUMCONF.setObjectName("TUMCONF")
        TUMCONF.resize(387, 732)
        self.centralwidget = QtWidgets.QWidget(TUMCONF)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCheckDevice = QtWidgets.QPushButton(self.centralwidget)
        self.btnCheckDevice.setObjectName("btnCheckDevice")
        self.horizontalLayout.addWidget(self.btnCheckDevice)
        self.lblDeviceID = QtWidgets.QLabel(self.centralwidget)
        self.lblDeviceID.setObjectName("lblDeviceID")
        self.horizontalLayout.addWidget(self.lblDeviceID)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabNetwork = QtWidgets.QWidget()
        self.tabNetwork.setObjectName("tabNetwork")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabNetwork)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnNetLoadConf = QtWidgets.QPushButton(self.tabNetwork)
        self.btnNetLoadConf.setObjectName("btnNetLoadConf")
        self.verticalLayout.addWidget(self.btnNetLoadConf)
        self.tabWidget = QtWidgets.QTabWidget(self.tabNetwork)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWired = QtWidgets.QWidget()
        self.tabWired.setObjectName("tabWired")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabWired)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rbtnIsDHCPWired = QtWidgets.QRadioButton(self.tabWired)
        self.rbtnIsDHCPWired.setIconSize(QtCore.QSize(30, 30))
        self.rbtnIsDHCPWired.setChecked(True)
        self.rbtnIsDHCPWired.setObjectName("rbtnIsDHCPWired")
        self.verticalLayout_3.addWidget(self.rbtnIsDHCPWired)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tabWired)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txtWiredIPWired = QtWidgets.QLineEdit(self.tabWired)
        self.txtWiredIPWired.setObjectName("txtWiredIPWired")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtWiredIPWired)
        self.label_3 = QtWidgets.QLabel(self.tabWired)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txtWiredMaskWired = QtWidgets.QLineEdit(self.tabWired)
        self.txtWiredMaskWired.setObjectName("txtWiredMaskWired")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtWiredMaskWired)
        self.label_4 = QtWidgets.QLabel(self.tabWired)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txtWiredGatewayWired = QtWidgets.QLineEdit(self.tabWired)
        self.txtWiredGatewayWired.setObjectName("txtWiredGatewayWired")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtWiredGatewayWired)
        self.label_5 = QtWidgets.QLabel(self.tabWired)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.txtWiredDNSWired = QtWidgets.QLineEdit(self.tabWired)
        self.txtWiredDNSWired.setObjectName("txtWiredDNSWired")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtWiredDNSWired)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.tabWidget.addTab(self.tabWired, "")
        self.tabWifi = QtWidgets.QWidget()
        self.tabWifi.setObjectName("tabWifi")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabWifi)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_10 = QtWidgets.QLabel(self.tabWifi)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.tabWifi)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.txtSSID = QtWidgets.QLineEdit(self.tabWifi)
        self.txtSSID.setObjectName("txtSSID")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtSSID)
        self.txtPasswordWifi = QtWidgets.QLineEdit(self.tabWifi)
        self.txtPasswordWifi.setObjectName("txtPasswordWifi")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtPasswordWifi)
        self.verticalLayout_4.addLayout(self.formLayout_4)
        self.line = QtWidgets.QFrame(self.tabWifi)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.rbtnIsDHCPWIFI = QtWidgets.QRadioButton(self.tabWifi)
        self.rbtnIsDHCPWIFI.setIconSize(QtCore.QSize(30, 30))
        self.rbtnIsDHCPWIFI.setChecked(True)
        self.rbtnIsDHCPWIFI.setObjectName("rbtnIsDHCPWIFI")
        self.verticalLayout_4.addWidget(self.rbtnIsDHCPWIFI)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.tabWifi)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.tabWifi)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.tabWifi)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.tabWifi)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.txtWiredIPWifi = QtWidgets.QLineEdit(self.tabWifi)
        self.txtWiredIPWifi.setObjectName("txtWiredIPWifi")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtWiredIPWifi)
        self.txtWiredMaskWifi = QtWidgets.QLineEdit(self.tabWifi)
        self.txtWiredMaskWifi.setObjectName("txtWiredMaskWifi")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtWiredMaskWifi)
        self.txtWiredGatewayWifi = QtWidgets.QLineEdit(self.tabWifi)
        self.txtWiredGatewayWifi.setObjectName("txtWiredGatewayWifi")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtWiredGatewayWifi)
        self.txtWiredDNSWifi = QtWidgets.QLineEdit(self.tabWifi)
        self.txtWiredDNSWifi.setObjectName("txtWiredDNSWifi")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtWiredDNSWifi)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabWifi, "")
        self.tabMobile = QtWidgets.QWidget()
        self.tabMobile.setObjectName("tabMobile")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabMobile)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.tabMobile)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.rbtnCMNET = QtWidgets.QRadioButton(self.tabMobile)
        self.rbtnCMNET.setObjectName("rbtnCMNET")
        self.verticalLayout_5.addWidget(self.rbtnCMNET)
        self.rbtnCMCC = QtWidgets.QRadioButton(self.tabMobile)
        self.rbtnCMCC.setObjectName("rbtnCMCC")
        self.verticalLayout_5.addWidget(self.rbtnCMCC)
        self.rbtnUNICOM = QtWidgets.QRadioButton(self.tabMobile)
        self.rbtnUNICOM.setObjectName("rbtnUNICOM")
        self.verticalLayout_5.addWidget(self.rbtnUNICOM)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.tabWidget.addTab(self.tabMobile, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.btnNetDownloadConf = QtWidgets.QPushButton(self.tabNetwork)
        self.btnNetDownloadConf.setObjectName("btnNetDownloadConf")
        self.verticalLayout.addWidget(self.btnNetDownloadConf)
        self.tabWidget_2.addTab(self.tabNetwork, "")
        self.tabTBD = QtWidgets.QWidget()
        self.tabTBD.setObjectName("tabTBD")
        self.tabWidget_2.addTab(self.tabTBD, "")
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        TUMCONF.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TUMCONF)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 387, 22))
        self.menubar.setObjectName("menubar")
        TUMCONF.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TUMCONF)
        self.statusbar.setObjectName("statusbar")
        TUMCONF.setStatusBar(self.statusbar)

        self.retranslateUi(TUMCONF)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TUMCONF)

    def retranslateUi(self, TUMCONF):
        _translate = QtCore.QCoreApplication.translate
        TUMCONF.setWindowTitle(_translate("TUMCONF", "传输单元配置工具"))
        self.btnCheckDevice.setText(_translate("TUMCONF", "检查设备"))
        self.lblDeviceID.setText(_translate("TUMCONF", "None"))
        self.btnNetLoadConf.setText(_translate("TUMCONF", "从设备加载配置"))
        self.rbtnIsDHCPWired.setText(_translate("TUMCONF", "动态IP(DHCP)"))
        self.label_2.setText(_translate("TUMCONF", "IP地址"))
        self.label_3.setText(_translate("TUMCONF", "子网掩码"))
        self.label_4.setText(_translate("TUMCONF", "默认网关"))
        self.label_5.setText(_translate("TUMCONF", "DNS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWired), _translate("TUMCONF", "有线"))
        self.label_10.setText(_translate("TUMCONF", "Wi-Fi名(SSID)"))
        self.label_11.setText(_translate("TUMCONF", "密码"))
        self.rbtnIsDHCPWIFI.setText(_translate("TUMCONF", "动态IP(DHCP)"))
        self.label_6.setText(_translate("TUMCONF", "IP地址"))
        self.label_7.setText(_translate("TUMCONF", "子网掩码"))
        self.label_8.setText(_translate("TUMCONF", "默认网关"))
        self.label_9.setText(_translate("TUMCONF", "DNS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWifi), _translate("TUMCONF", "Wi-Fi"))
        self.label_12.setText(_translate("TUMCONF", "网络类型"))
        self.rbtnCMNET.setText(_translate("TUMCONF", "电信"))
        self.rbtnCMCC.setText(_translate("TUMCONF", "移动"))
        self.rbtnUNICOM.setText(_translate("TUMCONF", "联通"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMobile), _translate("TUMCONF", "移动网络"))
        self.btnNetDownloadConf.setText(_translate("TUMCONF", "下发配置至设备"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabNetwork), _translate("TUMCONF", "网络功能"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabTBD), _translate("TUMCONF", "TBD"))


