# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TumConf.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(387, 732)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.lblDeviceID = QtWidgets.QLabel(self.centralwidget)
        self.lblDeviceID.setObjectName("lblDeviceID")
        self.horizontalLayout.addWidget(self.lblDeviceID)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabNetwork = QtWidgets.QWidget()
        self.tabNetwork.setObjectName("tabNetwork")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabNetwork)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnNetLoadConf = QtWidgets.QPushButton(self.tabNetwork)
        self.btnNetLoadConf.setObjectName("btnNetLoadConf")
        self.verticalLayout.addWidget(self.btnNetLoadConf)
        self.tabWidget = QtWidgets.QTabWidget(self.tabNetwork)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWired = QtWidgets.QWidget()
        self.tabWired.setObjectName("tabWired")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabWired)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.RBtnIsDHCP = QtWidgets.QRadioButton(self.tabWired)
        self.RBtnIsDHCP.setIconSize(QtCore.QSize(30, 30))
        self.RBtnIsDHCP.setChecked(True)
        self.RBtnIsDHCP.setObjectName("RBtnIsDHCP")
        self.verticalLayout_3.addWidget(self.RBtnIsDHCP)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tabWired)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txtWiredIP = QtWidgets.QLineEdit(self.tabWired)
        self.txtWiredIP.setObjectName("txtWiredIP")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtWiredIP)
        self.label_3 = QtWidgets.QLabel(self.tabWired)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txtWiredMask = QtWidgets.QLineEdit(self.tabWired)
        self.txtWiredMask.setObjectName("txtWiredMask")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtWiredMask)
        self.label_4 = QtWidgets.QLabel(self.tabWired)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txtWiredGateway = QtWidgets.QLineEdit(self.tabWired)
        self.txtWiredGateway.setObjectName("txtWiredGateway")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtWiredGateway)
        self.label_5 = QtWidgets.QLabel(self.tabWired)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.txtWiredDNS = QtWidgets.QLineEdit(self.tabWired)
        self.txtWiredDNS.setObjectName("txtWiredDNS")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtWiredDNS)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.tabWidget.addTab(self.tabWired, "")
        self.tabWifi = QtWidgets.QWidget()
        self.tabWifi.setObjectName("tabWifi")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabWifi)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_10 = QtWidgets.QLabel(self.tabWifi)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.tabWifi)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit = QtWidgets.QLineEdit(self.tabWifi)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tabWifi)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.verticalLayout_4.addLayout(self.formLayout_4)
        self.line = QtWidgets.QFrame(self.tabWifi)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.RBtnIsDHCP_2 = QtWidgets.QRadioButton(self.tabWifi)
        self.RBtnIsDHCP_2.setIconSize(QtCore.QSize(30, 30))
        self.RBtnIsDHCP_2.setChecked(True)
        self.RBtnIsDHCP_2.setObjectName("RBtnIsDHCP_2")
        self.verticalLayout_4.addWidget(self.RBtnIsDHCP_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.tabWifi)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.tabWifi)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.tabWifi)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.tabWifi)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.txtWiredIP_2 = QtWidgets.QLineEdit(self.tabWifi)
        self.txtWiredIP_2.setObjectName("txtWiredIP_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtWiredIP_2)
        self.txtWiredMask_2 = QtWidgets.QLineEdit(self.tabWifi)
        self.txtWiredMask_2.setObjectName("txtWiredMask_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtWiredMask_2)
        self.txtWiredGateway_2 = QtWidgets.QLineEdit(self.tabWifi)
        self.txtWiredGateway_2.setObjectName("txtWiredGateway_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtWiredGateway_2)
        self.txtWiredDNS_2 = QtWidgets.QLineEdit(self.tabWifi)
        self.txtWiredDNS_2.setObjectName("txtWiredDNS_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtWiredDNS_2)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabWifi, "")
        self.tabMobile = QtWidgets.QWidget()
        self.tabMobile.setObjectName("tabMobile")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabMobile)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.tabMobile)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.radioButton = QtWidgets.QRadioButton(self.tabMobile)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_5.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.tabMobile)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_5.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.tabMobile)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_5.addWidget(self.radioButton_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.tabWidget.addTab(self.tabMobile, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.btnNetDownloadConf = QtWidgets.QPushButton(self.tabNetwork)
        self.btnNetDownloadConf.setObjectName("btnNetDownloadConf")
        self.verticalLayout.addWidget(self.btnNetDownloadConf)
        self.tabWidget_2.addTab(self.tabNetwork, "")
        self.tabTBD = QtWidgets.QWidget()
        self.tabTBD.setObjectName("tabTBD")
        self.tabWidget_2.addTab(self.tabTBD, "")
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 387, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "检查设备"))
        self.lblDeviceID.setText(_translate("MainWindow", "None"))
        self.btnNetLoadConf.setText(_translate("MainWindow", "从设备加载配置"))
        self.RBtnIsDHCP.setText(_translate("MainWindow", "动态IP(DHCP)"))
        self.label_2.setText(_translate("MainWindow", "IP地址"))
        self.label_3.setText(_translate("MainWindow", "子网掩码"))
        self.label_4.setText(_translate("MainWindow", "默认网关"))
        self.label_5.setText(_translate("MainWindow", "DNS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWired), _translate("MainWindow", "有线"))
        self.label_10.setText(_translate("MainWindow", "Wi-Fi名(SSID)"))
        self.label_11.setText(_translate("MainWindow", "密码"))
        self.RBtnIsDHCP_2.setText(_translate("MainWindow", "动态IP(DHCP)"))
        self.label_6.setText(_translate("MainWindow", "IP地址"))
        self.label_7.setText(_translate("MainWindow", "子网掩码"))
        self.label_8.setText(_translate("MainWindow", "默认网关"))
        self.label_9.setText(_translate("MainWindow", "DNS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWifi), _translate("MainWindow", "Wi-Fi"))
        self.label_12.setText(_translate("MainWindow", "网络类型"))
        self.radioButton.setText(_translate("MainWindow", "电信"))
        self.radioButton_2.setText(_translate("MainWindow", "移动"))
        self.radioButton_3.setText(_translate("MainWindow", "联通"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMobile), _translate("MainWindow", "移动网络"))
        self.btnNetDownloadConf.setText(_translate("MainWindow", "下发配置至设备"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabNetwork), _translate("MainWindow", "网络功能"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabTBD), _translate("MainWindow", "TBD"))


